[project]
name = "slama"
description = "SMA LMA code"
authors = [
  { name = "Marc Pound", email = "mpound@umd.edu" },
  { name = "Peter Teuben", email = "teuben@umd.edu" },
]
readme = "README.md"
requires-python = ">=3.11"
keywords = []
dynamic = ["version"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "astropy>=7.0.1",
    "fastapi>=0.115.0",
    "jinja2>=3.1.0",
    "jsoneditor>=1.6.0",
    "matplotlib",
    "numpy",
    "pytest-timeout>=2.4.0",
    "pytest-xdist>=3.8.0",
    "smax",
    "treelib>=1.8.0",
    "uvicorn[standard]>=0.30.0",
]

[tool.uv.sources]
smax = { git = "ssh://git@github.com/Smithsonian/smax-python.git" }
