[project]
name = "slama"
description = "SMA LMA code"
authors = [
  { name = "Marc Pound", email = "mpound@umd.edu" },
  { name = "Peter Teuben", email = "teuben@umd.edu" },
]
readme = "README.md"
requires-python = ">=3.11"
keywords = []
dynamic = ["version"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
    "astropy>=7.0.1",
    "fastapi>=0.115.0",
    "fonttools>=4.60.2", # dependabot
    "ipython",
    "jinja2>=3.1.0",
    "jsoneditor>=1.6.0",
    "matplotlib",
    "pillow>=12.0.0",  # dependabot
    "requests>=2.33.0",  # dependabot
    "numpy",
    "smax",
    "treelib>=1.8.0",
    "urllib3>=2.7.0", #dependabot
    "uvicorn[standard]>=0.30.0",
]

#all = ["slama"]

[dependency-groups]
dev = [
  "coverage[toml]",
  #"myst-nb",
  #"nbclient",
  #"nbformat",
  "numpydoc",
  "pre-commit",
  "pytest",
  "pytest-cov",
  "pytest-xdist>=3.6.1",
  "pytest-timeout>=2.4.0",
  "ruff",
  "sphinx",
  "sphinx-autobuild",
  #"sphinx-book-theme",
  #"sphinx-copybutton",
  #"sphinx-design",
  #"sphinx-inline-tabs",
  #"sphinxcontrib-mermaid",
  "slama", # ensure that all extras are included in dev envs
]

[tool.uv.sources]
smax = { git = "https://github.com/Smithsonian/smax-python.git", rev="main" }

[tool.setuptools.dynamic]
version = {attr = "slama.__version__"}   
